/*
 * OpenAPI Implementation of Eth 2.0 
 *
 * Minimal OpenAPI specification for Spacemesh public facing API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// The [&#x60;DepositData&#x60;](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#depositdata) object from the Eth2.0 spec.
    /// </summary>
    [DataContract]
    public partial class DepositData : IEquatable<DepositData>
    { 
        /// <summary>
        /// Gets or Sets Pubkey
        /// </summary>
        [DataMember(Name="pubkey")]
        public Pubkey Pubkey { get; set; }

        /// <summary>
        /// The withdrawal credentials.
        /// </summary>
        /// <value>The withdrawal credentials.</value>
        [DataMember(Name="withdrawal_credentials")]
        public byte[] WithdrawalCredentials { get; set; }

        /// <summary>
        /// Amount in Gwei.
        /// </summary>
        /// <value>Amount in Gwei.</value>
        [DataMember(Name="amount")]
        public int? Amount { get; set; }

        /// <summary>
        /// Container self-signature.
        /// </summary>
        /// <value>Container self-signature.</value>
        [DataMember(Name="signature")]
        public byte[] Signature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class DepositData {\n");
            sb.Append("  Pubkey: ").Append(Pubkey).Append("\n");
            sb.Append("  WithdrawalCredentials: ").Append(WithdrawalCredentials).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((DepositData)obj);
        }

        /// <summary>
        /// Returns true if DepositData instances are equal
        /// </summary>
        /// <param name="other">Instance of DepositData to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DepositData other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Pubkey == other.Pubkey ||
                    Pubkey != null &&
                    Pubkey.Equals(other.Pubkey)
                ) && 
                (
                    WithdrawalCredentials == other.WithdrawalCredentials ||
                    WithdrawalCredentials != null &&
                    WithdrawalCredentials.Equals(other.WithdrawalCredentials)
                ) && 
                (
                    Amount == other.Amount ||
                    Amount != null &&
                    Amount.Equals(other.Amount)
                ) && 
                (
                    Signature == other.Signature ||
                    Signature != null &&
                    Signature.Equals(other.Signature)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Pubkey != null)
                    hashCode = hashCode * 59 + Pubkey.GetHashCode();
                    if (WithdrawalCredentials != null)
                    hashCode = hashCode * 59 + WithdrawalCredentials.GetHashCode();
                    if (Amount != null)
                    hashCode = hashCode * 59 + Amount.GetHashCode();
                    if (Signature != null)
                    hashCode = hashCode * 59 + Signature.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(DepositData left, DepositData right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(DepositData left, DepositData right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
