/*
 * OpenAPI Implementation of Spacemesh API 
 *
 * Minimal OpenAPI specification for Spacemesh public facing API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// The [&#x60;Fork&#x60;](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#Fork) object from the Eth2.0 spec.
    /// </summary>
    [DataContract]
    public partial class Fork : IEquatable<Fork>
    { 
        /// <summary>
        /// Previous fork version.
        /// </summary>
        /// <value>Previous fork version.</value>
        [DataMember(Name="previous_version")]
        public byte[] PreviousVersion { get; set; }

        /// <summary>
        /// Current fork version.
        /// </summary>
        /// <value>Current fork version.</value>
        [DataMember(Name="current_version")]
        public byte[] CurrentVersion { get; set; }

        /// <summary>
        /// Fork epoch number.
        /// </summary>
        /// <value>Fork epoch number.</value>
        [DataMember(Name="epoch")]
        public int? Epoch { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Fork {\n");
            sb.Append("  PreviousVersion: ").Append(PreviousVersion).Append("\n");
            sb.Append("  CurrentVersion: ").Append(CurrentVersion).Append("\n");
            sb.Append("  Epoch: ").Append(Epoch).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Fork)obj);
        }

        /// <summary>
        /// Returns true if Fork instances are equal
        /// </summary>
        /// <param name="other">Instance of Fork to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Fork other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    PreviousVersion == other.PreviousVersion ||
                    PreviousVersion != null &&
                    PreviousVersion.Equals(other.PreviousVersion)
                ) && 
                (
                    CurrentVersion == other.CurrentVersion ||
                    CurrentVersion != null &&
                    CurrentVersion.Equals(other.CurrentVersion)
                ) && 
                (
                    Epoch == other.Epoch ||
                    Epoch != null &&
                    Epoch.Equals(other.Epoch)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (PreviousVersion != null)
                    hashCode = hashCode * 59 + PreviousVersion.GetHashCode();
                    if (CurrentVersion != null)
                    hashCode = hashCode * 59 + CurrentVersion.GetHashCode();
                    if (Epoch != null)
                    hashCode = hashCode * 59 + Epoch.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Fork left, Fork right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Fork left, Fork right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
