/*
 * OpenAPI Implementation of Eth 2.0 
 *
 * Minimal OpenAPI specification for Spacemesh public facing API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// The [&#x60;IndexedAttestation&#x60;](https://github.com/ethereum/eth2.0-specs/blob/dev/specs/core/0_beacon-chain.md#indexedattestation) object from the Eth2.0 spec.
    /// </summary>
    [DataContract]
    public partial class IndexedAttestation : IEquatable<IndexedAttestation>
    { 
        /// <summary>
        /// Validator indicies for 0 bits.
        /// </summary>
        /// <value>Validator indicies for 0 bits.</value>
        [DataMember(Name="custody_bit_0_indicies")]
        public List<int?> CustodyBit0Indicies { get; set; }

        /// <summary>
        /// Validator indicies for 1 bits.
        /// </summary>
        /// <value>Validator indicies for 1 bits.</value>
        [DataMember(Name="custody_bit_1_indicies")]
        public List<int?> CustodyBit1Indicies { get; set; }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name="data")]
        public AttestationData Data { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IndexedAttestation {\n");
            sb.Append("  CustodyBit0Indicies: ").Append(CustodyBit0Indicies).Append("\n");
            sb.Append("  CustodyBit1Indicies: ").Append(CustodyBit1Indicies).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((IndexedAttestation)obj);
        }

        /// <summary>
        /// Returns true if IndexedAttestation instances are equal
        /// </summary>
        /// <param name="other">Instance of IndexedAttestation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IndexedAttestation other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CustodyBit0Indicies == other.CustodyBit0Indicies ||
                    CustodyBit0Indicies != null &&
                    CustodyBit0Indicies.SequenceEqual(other.CustodyBit0Indicies)
                ) && 
                (
                    CustodyBit1Indicies == other.CustodyBit1Indicies ||
                    CustodyBit1Indicies != null &&
                    CustodyBit1Indicies.SequenceEqual(other.CustodyBit1Indicies)
                ) && 
                (
                    Data == other.Data ||
                    Data != null &&
                    Data.Equals(other.Data)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CustodyBit0Indicies != null)
                    hashCode = hashCode * 59 + CustodyBit0Indicies.GetHashCode();
                    if (CustodyBit1Indicies != null)
                    hashCode = hashCode * 59 + CustodyBit1Indicies.GetHashCode();
                    if (Data != null)
                    hashCode = hashCode * 59 + Data.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(IndexedAttestation left, IndexedAttestation right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(IndexedAttestation left, IndexedAttestation right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
