/*
 * OpenAPI Implementation of Spacemesh API 
 *
 * Minimal OpenAPI specification for Spacemesh public facing API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class BuildApiController : ControllerBase
    { 
        /// <summary>
        /// Returns the github tag or branch used to build the node.
        /// </summary>
        /// <remarks>Requests the genesis_time parameter from the beacon node, which should be consistent across all beacon nodes that follow the same beacon chain.</remarks>
        /// <response code="200">Request successful</response>
        /// <response code="500">Beacon node internal error.</response>
        [HttpGet]
        [Route("/insight-dc-sv-2020/Spacemesh_Public_OpenAPI/1.0.0/node/genesis_time")]
        [ValidateModelState]
        [SwaggerOperation("NodeGenesisTimeGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(GenesisTime), description: "Request successful")]
        public virtual IActionResult NodeGenesisTimeGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(GenesisTime));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "1557716289";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<GenesisTime>(exampleJson)
                        : default(GenesisTime);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
