/*
 * OpenAPI Implementation of Spacemesh API 
 *
 * Minimal OpenAPI specification for Spacemesh public facing API.
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class OptionalApiController : ControllerBase
    { 
        /// <summary>
        /// Get fork information from running beacon node.
        /// </summary>
        /// <remarks>Requests the beacon node to provide which fork version it is currently on.</remarks>
        /// <response code="200">Request successful</response>
        /// <response code="500">Beacon node internal error.</response>
        [HttpGet]
        [Route("/insight-dc-sv-2020/geth/1.0.0/node/fork")]
        [ValidateModelState]
        [SwaggerOperation("NodeForkGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(InlineResponse2001), description: "Request successful")]
        public virtual IActionResult NodeForkGet()
        { 
            //TODO: Uncomment the next line to return response 200 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(200, default(InlineResponse2001));

            //TODO: Uncomment the next line to return response 500 or use other options such as return this.NotFound(), return this.BadRequest(..), ...
            // return StatusCode(500);
            string exampleJson = null;
            exampleJson = "{\n  \"fork\" : {\n    \"previous_version\" : \"\",\n    \"current_version\" : \"\",\n    \"epoch\" : 0\n  },\n  \"chain_id\" : 6\n}";
            
                        var example = exampleJson != null
                        ? JsonConvert.DeserializeObject<InlineResponse2001>(exampleJson)
                        : default(InlineResponse2001);            //TODO: Change the data returned
            return new ObjectResult(example);
        }
    }
}
